// core/constants.js - Application-wide constants

export const ADMIN_ROLES = {
  SUPERADMIN: "superadmin",
  TRAINER: "trainer",
  FINANCE: "finance",
};

export const MEMBER_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
  EXPIRED: "expired",
  ARCHIVED: "archived",
};

export const PAYMENT_STATUS = {
  PENDING: "pending",
  COMPLETED: "completed",
  FAILED: "failed",
  REFUNDED: "refunded",
};

export const PAYMENT_METHODS = {
  CASH: "cash",
  CARD: "card",
  BANK_TRANSFER: "bank_transfer",
  CHEQUE: "cheque",
  UPI: "upi",
  ONLINE: "online",
};

export const ACTION_TYPES = {
  // Admin actions
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
  ADMIN_CREATE_USER: "ADMIN_CREATE_USER",
  ADMIN_DELETE_USER: "ADMIN_DELETE_USER",
  ADMIN_UPDATE_USER: "ADMIN_UPDATE_USER",
  ADMIN_CHANGE_ROLE: "ADMIN_CHANGE_ROLE",

  // Member actions
  MEMBER_CREATE: "MEMBER_CREATE",
  MEMBER_UPDATE: "MEMBER_UPDATE",
  MEMBER_DELETE: "MEMBER_DELETE",
  MEMBER_ARCHIVE: "MEMBER_ARCHIVE",
  MEMBER_RESTORE: "MEMBER_RESTORE",

  // Package actions
  PACKAGE_CREATE: "PACKAGE_CREATE",
  PACKAGE_UPDATE: "PACKAGE_UPDATE",
  PACKAGE_DELETE: "PACKAGE_DELETE",

  // Payment actions
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",
  PAYMENT_DELETE: "PAYMENT_DELETE",
  PAYMENT_REFUND: "PAYMENT_REFUND",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  // Attendance actions
  ATTENDANCE_MARK: "ATTENDANCE_MARK",
  ATTENDANCE_CHECK_IN: "ATTENDANCE_CHECK_IN",
  ATTENDANCE_CHECK_OUT: "ATTENDANCE_CHECK_OUT",
  ATTENDANCE_LATE_ENTRY: "ATTENDANCE_LATE_ENTRY",
  ATTENDANCE_GYM_CLOSED: "ATTENDANCE_GYM_CLOSED",
  ATTENDANCE_SEARCH: "ATTENDANCE_SEARCH",
  ATTENDANCE_INVALID_INPUT: "ATTENDANCE_INVALID_INPUT",

  // Kiosk actions (public customer kiosk boundary)
  KIOSK_PUNCH: "KIOSK_PUNCH",
  KIOSK_AUTH_FAILED: "KIOSK_AUTH_FAILED",
  KIOSK_DISABLED: "KIOSK_DISABLED",
  KIOSK_ENABLED: "KIOSK_ENABLED",
  KIOSK_CREATE: "KIOSK_CREATE",
  KIOSK_UPDATE: "KIOSK_UPDATE",
  KIOSK_KEY_ROTATE: "KIOSK_KEY_ROTATE",
  KIOSK_DELETE: "KIOSK_DELETE",
  KIOSK_SCOPE_CHANGED: "KIOSK_SCOPE_CHANGED",

  // Trainer device activation (MODE 1)
  ACTIVATION_GENERATED: "ACTIVATION_GENERATED",
  ACTIVATION_REDEEMED: "ACTIVATION_REDEEMED",
  ACTIVATION_FAILED: "ACTIVATION_FAILED",
  ACTIVATION_REVOKED: "ACTIVATION_REVOKED",
  DEVICE_ACTIVATED: "DEVICE_ACTIVATED",
  DEVICE_DEACTIVATED: "DEVICE_DEACTIVATED",
  DEVICE_REVOKED: "DEVICE_REVOKED",
  SCOPE_CHANGED: "SCOPE_CHANGED",

  // Super Admin attendance (MODE 2)
  SUPERADMIN_ATTENDANCE_SCOPE_SELECTED: "SUPERADMIN_ATTENDANCE_SCOPE_SELECTED",

  // Other
  EXPORT_DATA: "EXPORT_DATA",
  IMPORT_DATA: "IMPORT_DATA",
};

export const LOG_LEVELS = {
  DEBUG: "debug",
  INFO: "info",
  WARN: "warn",
  ERROR: "error",
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
